server:
  port: 8084
   
spring:
  cloud:
    gateway:
      routes:
      - id: btcorder_api
        uri: http://localhost:8081
        predicates:
        - Method=GET
        - Path=/btcorders/
        filters:
        - RewritePath=/btcorders, /btcorderapi
                
      - id: btborder_api
        uri: http://localhost:8082
        predicates:
        - Method=GET
        - Path=/btborders/  
        filters:
        - RewritePath=/btborders, /btborderapi      
      
      
